# Generated by Django 3.2.6 on 2021-09-02 06:01

import os

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        DJANGO_SU_NAME = os.environ.get('DJANGO_SU_NAME')
        DJANGO_SU_EMAIL = os.environ.get('DJANGO_SU_EMAIL')
        DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SU_PASSWORD')

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_NAME,
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD
        )

        superuser.save()

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('technology', models.CharField(blank=True, max_length=20)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('some_field', models.CharField(blank=True, max_length=20)),
                ('image', models.FilePathField(blank=True, path='projects/static/projects/')),
            ],
        ),
        migrations.RunPython(generate_superuser)
    ]
