# Generated by Django 3.2.6 on 2021-09-03 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='some_field',
        ),
    ]
