# Generated by Django 3.2.6 on 2021-09-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
