# Generated by Django 3.2.6 on 2021-09-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, upload_to='projects/uploads/%Y/%m/%d/'),
        ),
    ]
