# Generated by Django 3.2.6 on 2021-09-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='Test'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Test', max_length=20),
        ),
    ]
