# Generated by Django 3.2.6 on 2021-09-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Test', max_length=50),
        ),
    ]
