# Generated by Django 3.2.6 on 2021-09-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_categories_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
