# Generated by Django 3.2.6 on 2021-09-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_liked',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_liked',
            field=models.BooleanField(null=True),
        ),
    ]
