# Generated by Django 3.2.6 on 2021-09-13 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210913_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_liked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_liked',
        ),
    ]
